name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**'

  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        test-type: [test, coverage]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test or coverage
      run: |
        npm install
        if [ "${{ matrix.test-type }}" = "test" ]; then
          npm test
        else
          npm run coverage:action
        fi  
        
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      if: matrix.test-type == 'coverage'
      env:
        CI: true
